### PR TITLE
New news

### PR DESCRIPTION
**Pull request by copperstick6**
added florian banker

### CODE REVIEW

**Comment by theBrianCui** [comment]
Lol why are there .DS_Store files in the commit

Mac OS pls

**Comment by copperstick6** [comment]
IM SORRY

**Comment by theBrianCui** [comment]
Dude, you killed welcome.hbs again.

Can you test what you're doing **before** submitting a PR?

**Comment by copperstick6** [comment]
I did it was fine when I tested it

**Comment by copperstick6** [comment]
its the Mac thing man

**Comment by copperstick6** [comment]
fixed the icon

**Pull request closed without merging**
